### ISSUE TITLE
Desktop files with manually-set "Name" are not translated

### ISSUE THREAD

**Issue by n8marti** [wasta-linux/wasta-multidesktop-focal#1]
_I'm curious to see if this is a viable way to discuss code changes_

When using a non-English locale (French in my case) the manually-set "Name" fields in desktop files are not translated. So I have a properly-translated "Software" app as "Logiciel", but then "Software Settings" is still "Software Settings" (see screenshot below). I think the solution might be to rename it using:
> $ desktop-file-edit --set-key='Name[en]' --set-value='Software Settings' /usr/share/applications/software-properties-{gnome|gtk}.desktop # <-- pseudo code alert!

rather than:

> $ desktop-file-edit --set-name="Software Settings" /usr/share/applications/software-properties-{gnome|gtk}.desktop

I found 7 instances of "--set-name" in app-adjustments.sh that I think could benefit from being tweaked in this same way.

What I'm less sure about, though, is how to reset then generic "Name" entry at the same time. What is the original value for "Name" for each of those?

![2020-08-13 10:15:59](https://user-images.githubusercontent.com/23388501/90117351-b27dd500-dd4e-11ea-8f7d-37820ddcfb04.png)

**Comment by n8marti** [comment]
Okay, I managed to edit all the changed entries (any that used --set-name or --set-comment) so that "Name" and "Comment" keys were defaults (as found in the respective original source code files, see link below), and then the text used in app-adjustments for each one was moved to "Name[en]" and "Comment[en]", respectively. This allows for me to add custom text for French, as well as all "Name" and "Comment" keys to be properly displayed, regardless of whether I choose English or French as the User language.

You can see what I did in the custom-car [postinst script](https://github.com/wasta-linux/wasta-custom-car/blob/master/wasta-custom-car/wasta-custom-car-postinst.sh#L337), Lines 338-432.

**Comment by rik-shaw** [comment]
@n8marti looks like a good approach. I think we could do similar for wasta-multidesktop. As more supported languages come into the Wasta fold we may want to have these translations in some external file, but I haven't gotten my head around how to do that yet.

Note that a lot of motivation for my tweaking name, comment, or adding a keyword is so that in the Cinnamon Menu things would properly be "found". They do some logic so if what you type is in the NAME of an app it is found, but if something found by NAME then if it is only in the comment it will NOT be found. Stuff like that is why I name it "Synaptic Software Package Manager" or else a search for "software" was not showing Synaptic.

Since you are focusing on Gnome you may not need to do such tricks for your users, but keep it in mind if when doing French searches and you aren't finding something you know should show.

I THINK newer cinnamon versions will search on the "Keywords" field: in older versions this wasn't looked at. Not sure but think Gnome is also looking at that field. So it is good to stash search terms here.... but again cinnamon does additional logic to not show too many results so it isn't always the *only* place that a search term may need to be added.

**Comment by rik-shaw** [comment]
You interested to do a pull request with these fixes? "PRs welcome :-)"

**Comment by n8marti** [comment]
Sure thing. I'll work on that this week.

Le 16/08/2020 à 16:37, Rik Shaw a écrit :

**Comment by n8marti** [comment]
@rik-shaw There are a few apps that I don't have installed in bionic or focal but have desktop file modifications in app-adjustments. Are these legacy apps that can be ignored? Or are they specifically used by other Wasta maintainers? Or am I overlooking something?
- org.gnome.Packages.desktop
- software-properties-gnome.desktop
- gnome-search-tool.desktop

**Comment by rik-shaw** [comment]
These updates are being handled by pull request #2

**Comment by rik-shaw** [comment]
Closed
